---
  tasks:
    - name: "Create User {{ item.username }} and configure sudo block."
      block:
        - name: "Create User {{ item.username }}."
          user:
            name: "{{ item.username }}"
            password: "{{ item.password }}"
            create_home: true
            groups: "users,mail,{{ sudo_group }}"
            shell: /bin/bash
            expires: -1

        - name: "Create .ssh folder for {{ item.username }}."
          file:
            path: "/home/{{ item.username }}/.ssh"
            state: directory

        - name: Check if running from Vagrant or other method, by checking User vagrant folder
          stat: path=/home/vagrant
          register: st

        - name: "Append user Public key to Authorized_keys for {{ item.username }}."
          shell: "cat /home/vagrant/.ssh/me.pub >> /home/{{ item.username }}/.ssh/authorized_keys"
          args:
            creates: "/home/{{ item.username }}/.ssh/authorized_keys"
          when: st.stat.exists

        - name: "Copy user Public key to Authorized_keys for {{ item.username }}."
          shell: "cat /root/.ssh/authorized_keys >> /home/{{ item.username }}/.ssh/authorized_keys"
          args:
            creates: "/home/{{ item.username }}/.ssh/authorized_keys"
          when: not st.stat.exists

        - name: "Add NOPASSWD Sudo into SUDOERS for {{ item.username }}."
          lineinfile:
            path: /etc/sudoers
            line: "{{ item.username }}        ALL=(ALL)       NOPASSWD: ALL"
            validate: /usr/sbin/visudo -cf %s

        - name: "Set Home directory ownership - {{ item.username }}."
          file:
            path: "/home/{{ item.username }}"
            owner: "{{ item.username }}"
            group: "{{ item.username }}"
            recurse: true
