---
# tasks file for hammadrauf.ansible-role-apache2
- debug: var=ansible_os_family
- name: Load OS specific Vars file
  include_vars: "{{ item }}"
  with_first_found:
    - "./vars/os_specific_{{ ansible_os_family }}.yml"
    - "./vars/os_specific_default.yml"    

- name: Repeat createuser block with loop
  ansible.builtin.include_tasks: createuser.yml
  with_items:
    - "{{ users }}"

- name: Play - Install Apache
  hosts: all
  vars_files:
    - ./vars/vars.yml
    - ./vars/secrets.yml
  remote_user: "{{ vmuser1 }}"

  pre_tasks:
    - debug: var=ansible_os_family
    - name: Load OS specific Vars file
      include_vars: "{{ item }}"
      with_first_found:
        - "./vars/os_specific_{{ ansible_os_family }}.yml"
        - "./vars/os_specific_default.yml"

  tasks:
    - name: Install package Apache
      package:
        name: "{{ vapache }}"
        state: present
      become: true

    - name: Enable the Apache Service, if not already done so
      service: 
        name: "{{ vapache_service }}"
        enabled: true
      become: true

    - name: Start the Apache Service, if not already done so
      service: 
        name: "{{ vapache_service }}"
        state: started
      become: true

    - name: Check if Apache Default Content folder exists
      stat: path="{{ vapache_default_content }}"
      register: apc

    - name: Delete the pre-packeged files from Apache Default Content folder
      shell: "/usr/bin/rm -rf {{ vapache_default_content }}/* && /usr/bin/find {{ vapache_default_content }}/ -name '.*' ! -name '.' ! -name '..' -delete"
      args:
        removes: "{{ vapache_default_content }}/index.html"
      become: true
      when: apc.stat.exists
      
    - name: Copy the included index.html from Host to remote in the Apache Default Content folder
      copy:
        src: ./script-uploaded-files/index.html
        dest: "{{ vapache_default_content }}/index.html"
        owner: "{{ vapache_user }}"
        group: "{{ vapache_group }}"
        mode: '0644'
      become: true
      when: apc.stat.exists      

    - name: Copy the included site_styles.css from Host to remote in the Apache Default Content folder
      copy:
        src: ./script-uploaded-files/site_styles.css
        dest: "{{ vapache_default_content }}/site_styles.css"
        owner: "{{ vapache_user }}"
        group: "{{ vapache_group }}"
        mode: '0644'
      become: true
      when: apc.stat.exists

    - name: Copy the included icon from Host to remote in the Apache Default Content folder
      copy:
        src: ./script-uploaded-files/castle-icon.ico
        dest: "{{ vapache_default_content }}/favicon.ico"
        owner: "{{ vapache_user }}"
        group: "{{ vapache_group }}"
        mode: '0644'
      become: true
      when: apc.stat.exists

    - name: Re-Start the Apache Service.
      service: 
        name: "{{ vapache_service }}"
        state: restarted
      become: true
      when: apc.stat.exists

    - name: Gather the installed package facts
      ansible.builtin.package_facts:
        manager: auto      
      when: ansible_os_family == "RedHat"

    - name: If FirewallD is installed then open 'http' port
      ansible.posix.firewalld: 
        service: http
        permanent: true
        state: enabled
      become: true
      when:  ansible_os_family == "RedHat" and "'firewalld' in ansible_facts.packages"

    - name: Re-Start the Firewalld Service
      service: 
        name: "firewalld"
        state: restarted
      become: true
      when: ansible_os_family == "RedHat" and "'firewalld' in ansible_facts.packages"
