---
driver:
  name: default
  options:
    managed: false
    login_cmd_template: 'docker exec -ti {instance} bash'
    ansible_connection_options:
      ansible_connection: docker    
platforms:
  - name: debian12
    image: docker.io/hammadrauf/debian12:latest
  - name: rhel8
    image: docker.io/roboxes/rhel8
# - name: ubuntu
#   image: docker.io/ubuntu:noble
